backend = "kmeans"
color_space = "labmixed"
palette = "dark16"

[templates.waybar]
template = "/home/patrick/.config/wallust/templates/waybar/style.css.j2"
target = "/home/patrick/.config/waybar/style.css"

[templates.swaylock]
template = "/home/patrick/.config/wallust/templates/swaylock/config.j2"
target = "/home/patrick/.config/swaylock/config"

[templates.mako]
template = "/home/patrick/.config/wallust/templates/mako/config.j2"
target = "/home/patrick/.config/mako/config"

[templates.rofi]
template = "/home/patrick/.config/wallust/templates/rofi/config.rasi.j2"
target = "/home/patrick/.config/rofi/config.rasi"

[templates.foot]
template = "/home/patrick/.config/wallust/templates/foot/foot.ini.j2"
target = "/home/patrick/.config/foot/foot.ini"
