preload = ~/Pictures/wallpapers/ocean_with_cloud.png
preload = ~/Pictures/wallpapers/gruvbox_forest-4.png
preload = ~/Pictures/wallpapers/van.png
preload = ~/Pictures/wallpapers/sunset-xfksfuywx.png
preload = ~/Pictures/wallpapers/wallhaven-zpoxyj.png
preload = ~/Pictures/wallpapers/wallhaven-yqg6r7.jpg

wallpaper = , ~/Pictures/wallpapers/ocean_with_cloud.png
