general {
    lock_cmd = hyprlock
    unlock_cmd = notify-sent "unlocked"
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 300
    on-timeout = hyprlock
}

listener {
    timeout = 600
    on-timeout = dpms off
}
